"""remove unique constraint from sns_id

Revision ID: 6cc1fc8cdac6
Revises: b0b4ce5b5925
Create Date: 2025-11-16 16:13:25.377019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc1fc8cdac6'
down_revision: Union[str, None] = 'b0b4ce5b5925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sns_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('sns_id', 'users', ['sns_id'], unique=True)
    # ### end Alembic commands ###
