"""add related_request_id column

Revision ID: 75a9d7c07d45
Revises: fcd3b412877c
Create Date: 2025-11-22 20:51:48.160871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '75a9d7c07d45'
down_revision: Union[str, None] = 'fcd3b412877c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet_share_requests', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet_share_requests', sa.Column('message', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
