"""add finish location

Revision ID: cf09eb8815a8
Revises: d8cae66f3557
Create Date: 2025-11-26 19:06:04.917940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf09eb8815a8'
down_revision: Union[str, None] = 'd8cae66f3557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walks', sa.Column('last_lat', sa.Float(), nullable=True))
    op.add_column('walks', sa.Column('last_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('walks', 'last_lng')
    op.drop_column('walks', 'last_lat')
    # ### end Alembic commands ###
