"""add related_request_id remove is_read

Revision ID: fcd3b412877c
Revises: b81688d20eba
Create Date: 2025-11-22 16:56:53.454276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fcd3b412877c'
down_revision: Union[str, None] = 'b81688d20eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('related_request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'pet_share_requests', ['related_request_id'], ['request_id'])
    op.drop_column('notifications', 'is_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'related_request_id')
    # ### end Alembic commands ###
